# Generated by Django 3.0.1 on 2019-12-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='image',
            field=models.URLField(default='https://media.comicbook.com/2019/08/dbz-goku-vs-freeza-1185151-1280x0.jpeg', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
